title: "Plastics ♹"
email: me@stephencorwin.com
description: >-
  Complexity and culture.
baseurl: ""
url: "https://plasticspod.org"

# Build settings
remote_theme: riggraz/no-style-please
permalink: /writing/:slug/

theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
